### ISSUE TITLE
react-typescript-cheatsheet

### ISSUE THREAD

**Issue by ghost** [qti3e/boilerplate#1]
Hi :wave: 

Just in case you don't know about this repo (https://github.com/sw-yx/react-typescript-cheatsheet)
Good luck :smiley:

**Comment by qti3e** [comment]
Hi @Attrash-Islam!
Sorry for responding to you late, I've hit unwatch button accidentally, so I didn't get any notification : (

I just looked at it right now, but I didn't get what it truly does at first glance I'll take another look soon : )
